# Publish GitHub Pages
# azure-pipelines.yml

trigger:
- master


steps:
- script: |
    git config --local user.name "tlpz-docs"
    git config --local user.email "tkonradsson@vectoritcgroup.com"
    git add .
    git commit -m "Publishing GitHub Pages  ***NO_CI***"
  displayName: 'Build and commit pages'

- task: DownloadSecureFile@1
  inputs:
    secureFile: deploy_key
  displayName: 'Get the deploy key'

- script: |
    git remote set-url --push origin git@github.com:tlpz-docs/tlpz-docs.github.io.git
    git push origin HEAD:master
  displayName: 'Publish GitHub Pages'
  condition: |
    and(not(eq(variables['Build.Reason'], 'PullRequest')),
        eq(variables['Build.SourceBranch'], 'refs/heads/master'))
